spring.datasource:
  name: aaa_ds
  # https://jdbc.postgresql.org/documentation/head/connect.html#connection-parameters
  url: jdbc:postgresql://127.0.0.1:35432/aaa?connectTimeout=10&socketTimeout=40&ApplicationName=aaa-app
  username: aaa
  password: "aaaPazZw0rd"
